--- 
- hosts: centos
  tasks:
    - name: Ensure epel repository is set
      yum:
        name: epel-release
        state: latest
      become: true    

    # System update
    - name: Ensure all pkgs are up-to-date
      yum:
         name: '*'
         state: latest
      become: true
      tags: update

    # Install packages
    - name: Ensure system RPMs are installed and up-to-date
      yum: 
        pkg: "{{ item }}"
        state: latest
      become: true
      with_items:
         - yum-utils
         - net-tools
         - curl
         - vim
         - htop
         - epel-release
          
  







 


